name: Build Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: qtmultimedia
          cache: true

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build --config Release

      - name: Deploy Qt
        run: |
          mkdir package
          windeployqt --release --no-translations --compiler-runtime --dir package build/TimerApp.exe

      - name: Copy sound
        run: |
          mkdir package/sounds
          copy sounds/timer.wav package/sounds/timer.wav

      - name: Upload Windows package
        uses: actions/upload-artifact@v4
        with:
          name: Timer-Windows
          path: package
